on:
  schedule: [{ cron: "0 2 * * *" }]  # 02:00 UTC ≈ 03:00 CET
  workflow_dispatch: {}

jobs:
  reseed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # action checkout v6
        with:
            ref: main

      - uses: supabase/setup-cli@aa3515eac405eac768fa4a72147c22d88a283c7b
        name: Install supabase CLI
        with:
          version: latest

      - name: Link to cloud instance
        env:
          SUPABASE_ACCESS_TOKEN: ${{secrets.SUPABASE_ACCESS_TOKEN}}
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Reset storage buckets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
        run: bun scripts/reset-buckets.mjs

      - name: Reset instance
        env:
          SUPABASE_ACCESS_TOKEN: ${{secrets.SUPABASE_ACCESS_TOKEN}}
        run: |
          supabase db reset --linked --yes
          supabase config push

      - name: Stop supabase
        run: supabase stop